add test-complete job to make it an aggregate check for all test jobs that generated from matrix strategy

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,4 +29,17 @@ jobs:
             - name: Run Tests
               run: |
                 pytest
-              
+    test-complete:
+        name: test
+        needs: test
+        runs-on: ubuntu-latest
+
+        if: always()
+
+        steps:
+            - name: Fail if any matrix job failed
+              run: |
+                if [[ "${{ needs.test.result }}" != "success" ]]; then
+                    echo "Some matrix jobs failed"
+                    exit 1
+                fi
